sonar.projectKey=AndreaPastourel_CesiZen
sonar.organization=andreapastourel

sonar.projectName=CesiZen
sonar.sourceEncoding=UTF-8

sonar.sources=web-react/src,CesiZen_API/src

sonar.tests=web-react/src,CesiZen_API/tests

sonar.exclusions=\
  **/vendor/**,\
  **/dist/**,\
  **/build/**,\
  **/coverage/**,\
  **/var/**

sonar.test.inclusions=\
  web-react/src/**/*.test.*,\
  web-react/src/**/*.spec.*,\
  CesiZen_API/tests/**/*.php
