sonar.projectKey=AndreaPastourel_CesiZen
sonar.organization=andreapastourel

sonar.projectName=CesiZen
sonar.sourceEncoding=UTF-8

sonar.sources=web-react/src,api-symfony/src

sonar.tests=web-react/src,api-symfony/tests

sonar.exclusions=\
  **/node_modules/**,\
  **/vendor/**,\
  **/dist/**,\
  **/build/**,\
  **/coverage/**,\
  **/var/**

sonar.test.inclusions=\
  web-react/src/**/*.test.*,\
  web-react/src/**/*.spec.*,\
  api-symfony/tests/**/*.php
