name: Back - Security

on:
  push:
    branches:
      - "**"
    paths:
      - "CesiZen_API/**"
      - ".github/workflows/ci-security-back.yml"

  pull_request:
    branches:
      - main
      - dev
    paths:
      - "CesiZen_API/**"
      - ".github/workflows/ci-security-back.yml"

jobs:
  dependency-scan:
    name: Analyse des dépendances
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api-symfony

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Installation des dépendances
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Audit Composer
        run: composer audit
        continue-on-error: true

  semgrep:
    name: Analyse Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Semgrep
        run: pip install semgrep

      - name: Scan Semgrep
        run: semgrep scan --config auto api-symfony
