# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    App\Controller\RessourcesListController:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\RessourceBySlugController:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\RessourceByIdController:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\TypesEmotionsController:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\EmotionsController:
        autowire: true
        autoconfigure: true
        public: true


    App\Controller\EmotionByIdController:
        autowire: true
        autoconfigure: true
        public: true
    
    App\Controller\TypeEmotionByIdController:
        autowire: true
        autoconfigure: true
        public: true