sonar.projectKey=AndreaPastourel_CesiZen
sonar.organization=andreapastourel

sonar.projectName=CesiZen-Front
sonar.sourceEncoding=UTF-8

sonar.sources=src

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/tests/** 
