name: Front - SonarCloud

on:
  push:
    branches:
      - main
      - dev
      - "**"

  pull_request:
    branches:
      - main
      - dev

jobs:
  sonar:
    name: Analyse SonarCloud
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web-react

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: web-react/package-lock.json

      - name: Installation des dépendances
        run: npm ci

      - name: Build du projet
        run: npm run build

      - name: Analyse SonarCloud
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: web-react
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}