name: Global - Secrets

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main
      - dev

jobs:
  secret-scan:
    name: Recherche de secrets
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan Gitleaks
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            zricethezav/gitleaks:latest \
            detect \
            --source="/repo" \
            --verbose