name: Back - Tests

on:
  push:
    branches:
      - "**"
    paths:
      - "CesiZen_API/**"
      - ".github/workflows/ci-tests-back.yml"

  pull_request:
    branches:
      - main
      - dev
    paths:
      - "CesiZen_API/**"
      - ".github/workflows/ci-tests-back.yml"

jobs:
  tests:
    name: Tests PHPUnit
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: CesiZen_API

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, intl
          coverage: none

      - name: Installation des dépendances
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Tests unitaires
        run: php bin/phpunit