name: Front - OWASP ZAP

on:
  push:
    branches:
      - "**"
    paths:
      - "web-react/**"
      - ".github/workflows/ci-zap-front.yml"

  pull_request:
    branches:
      - main
      - dev
    paths:
      - "web-react/**"
      - ".github/workflows/ci-zap-front.yml"

jobs:
  zap-scan:
    name: Scan OWASP ZAP
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web-react

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Construction de l’image Docker
        run: docker build --tag cesizen-front-zap .

      - name: Démarrage du conteneur front
        run: |
          docker run \
            --detach \
            --name cesizen-front-zap \
            --publish 4173:8080 \
            cesizen-front-zap

      - name: Attente du démarrage
        run: |
          for i in {1..30}; do
            if curl -f http://127.0.0.1:4173 > /dev/null 2>&1; then
              echo "Front disponible"
              exit 0
            fi

            echo "Attente du front..."
            sleep 2
          done

          echo "Le front n'a pas démarré"
          exit 1

      - name: Scan OWASP ZAP
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: "http://127.0.0.1:4173"
          allow_issue_writing: false
          fail_action: true

      - name: Arrêt du conteneur front
        if: always()
        run: docker rm --force cesizen-front-zap || true